### ISSUE TITLE
创建文章时报错

### ISSUE THREAD

**Issue by taozhiyuzhuo** [luoyangpeng/Ladmin#1]
1.创建文章的时候数据库报错
`null value in column "view_count"`
2.文章添加图片从本地上传无法使用
3.提交之后如果报错，返回之后文章没有了

**Comment by luoyangpeng** [comment]
你设置 view_count 默认值为0。
文章添加封面图片的bug已修复，你更新下。

**Comment by taozhiyuzhuo** [comment]
封面图片没有问题,文章内容添加图片的时候无法从本地上传只能从图片库里选择

**Comment by luoyangpeng** [comment]
这个是没有的。这段时间公司事情太多了。明天还得加班。等有时间会加上，可以直接上传，也可以从图片库选择图片这个功能。
